include CommonDefs.mak

BIN_DIR = Bin

INC_DIRS = \
	Common \
	../Include \
	../../External/GL \
	$(OPENNI2_INCLUDE) \
	$(NITE2_INCLUDE)

SRC_FILES = main.cpp kinect.cpp

ifeq ("$(OSTYPE)","Darwin")
	CFLAGS += -DMACOS
	LDFLAGS += -framework OpenGL -framework GLUT
else
	CFLAGS += -DUNIX -DGLX_GLXEXT_LEGACY
	USED_LIBS += glut GL
endif

LIB_DIRS += $(OPENNI2_REDIST) $(NITE2_REDIST64)

USED_LIBS += OpenNI2 NiTE2

EXE_NAME = UserViewer

CFLAGS += -Wall -I.

include CommonCppMakefile
