#!/bin/sh
usage="Data selection

Usage:
  data_select <data-file> <dir-output>

Read the <data-file> file and take the tree last columns of the
lines beginning by \"A \", \"G \" and \"C \" into, respectively
<dir-output>/thread_A.dat, <dir-output>/thread_G.dat and
<dir-output>/thread_C.dat.
"

[ "$#" -ne 1 ] && echo "$usage" && exit 1
cat $1 | grep "^A " | awk '{print $(NF - 2)" "$(NF - 1)" "$(NF)}' > $2/thread_A.dat
cat $1 | grep "^G " | awk '{print $(NF - 2)" "$(NF - 1)" "$(NF)}' > $2/thread_G.dat
cat $1 | grep "^C " | awk '{print $(NF - 2)" "$(NF - 1)" "$(NF)}' > $2/thread_C.dat
